version: '3.1'

services:
  notebook:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - .:/home/jovyan/work

#  cassandra:
#    image: 'bitnami/cassandra:latest'

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'school'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
